<a href="https://colab.research.google.com/github/yablockoo/GB/blob/PyTorch/PyTorchHW01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
# Создайте случайный FloatTensor размера 3x4x5

a = torch.rand(3, 4, 5).type(torch.float32)

In [ ]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [ ]:
# Приведите его к форме 6 X 10
a = a.view(6, 10) 
a

tensor([[0.9476, 0.8133, 0.7539, 0.6700, 0.5153, 0.1373, 0.9423, 0.2586, 0.0549,
         0.6897],
        [0.6774, 0.9706, 0.1530, 0.3408, 0.9573, 0.4512, 0.3232, 0.3198, 0.4859,
         0.3903],
        [0.0598, 0.6495, 0.6289, 0.8088, 0.8690, 0.2981, 0.6699, 0.7258, 0.2100,
         0.6118],
        [0.5754, 0.3942, 0.9995, 0.6091, 0.2687, 0.1911, 0.2438, 0.8157, 0.1183,
         0.6727],
        [0.3355, 0.3316, 0.9376, 0.7856, 0.6430, 0.3950, 0.8995, 0.7088, 0.6559,
         0.4415],
        [0.9399, 0.7153, 0.4676, 0.0317, 0.5157, 0.7771, 0.2133, 0.3156, 0.2526,
         0.2002]])

In [ ]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
b = torch.FloatTensor([1, 4, 2, 2, 1, 1]) 
c = a.view(10, 6) * b
c

tensor([[0.9476, 3.2533, 1.5078, 1.3399, 0.5153, 0.1373],
        [0.9423, 1.0345, 0.1097, 1.3794, 0.6774, 0.9706],
        [0.1530, 1.3634, 1.9147, 0.9024, 0.3232, 0.3198],
        [0.4859, 1.5614, 0.1196, 1.2990, 0.6289, 0.8088],
        [0.8690, 1.1924, 1.3398, 1.4515, 0.2100, 0.6118],
        [0.5754, 1.5768, 1.9990, 1.2181, 0.2687, 0.1911],
        [0.2438, 3.2629, 0.2367, 1.3454, 0.3355, 0.3316],
        [0.9376, 3.1423, 1.2860, 0.7901, 0.8995, 0.7088],
        [0.6559, 1.7660, 1.8798, 1.4306, 0.4676, 0.0317],
        [0.5157, 3.1084, 0.4265, 0.6313, 0.2526, 0.2002]])

In [ ]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
d = c.view(6, 10).mm(c)
d.shape

torch.Size([6, 6])

In [ ]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.Tensor([1]), requires_grad = True)
z = Variable(torch.Tensor([0.5]), requires_grad = True)
t = Variable(torch.Tensor([2]), requires_grad = True)

In [ ]:
y = x**3 + z - 75 * t

In [ ]:
y.backward(inputs=(x, z, t))

In [ ]:
print(x.grad, z.grad, t.grad)

tensor([3.]) tensor([1.]) tensor([-75.])


In [ ]:
# Создайте единичный тензор размера 5x6
x = torch.ones(5, 6)
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Переведите его в формат numpy
xnp = x.numpy()
xnp

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
from torch import nn 
from torch import optim