<a href="https://colab.research.google.com/github/yablockoo/GB/blob/Intensive/%D0%94%D0%97_%D0%97%D0%BD%D0%B0%D0%BA%D0%BE%D0%BC%D1%81%D1%82%D0%B2%D0%BE_%D1%81_%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0%D0%BC%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pandas

Для некоторых заданий, возможно, придется обратиться к документации: https://pandas.pydata.org/docs/

* Скачайте любой табличный датасет (или создайте тестовый пример самостоятельно), например, с https://www.kaggle.com/datasets

*  Загрузите данные и проанализируйте их (используя функции .info и .describe)
*  Выведите отдельно интересующую вас колонку и столбец

### Numpy

Для некоторых заданий, возможно, придется обратиться к документации: https://numpy.org

* Создайте вектор (одномерный массив) размера 10, заполненный нулями
* Создайте вектор размера 10, заполненный числом 5.8
* Создйте массив 3x3x3 со случайными значениями
* Создайте 8x8 матрицу и заполнить её в шахматном порядке
* Cоздайте матрицу 4 на 4 и заполните ее произвольными числами (понадобиться в дальйнешем)

### Scipy


* Возьмите интеграл $\int_{-3}^{10} sin(x)* x^{2} \,dx $
* Найдите определитель, обратную матрицу и собственные значения к матрице из последнего пункта раздела Numpy


### Matplotlib/Seaborn


* Нарисуйте график sin(x), подпишите оси, добавьте сетку
* Нарисуйте график sin(x) и cos(x) на одном subplot'е и на разных, задайте цвета, которые вам больше нравятся



---



* Скачайте любой табличный датасет (или создайте тестовый пример самостоятельно), например, с https://www.kaggle.com/datasets

* Загрузите данные и проанализируйте их (используя функции .info и .describe)

* Выведите отдельно интересующую вас колонку и столбец


In [4]:
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/data/India_Menu.csv')
data.head(5)

Menu Category              Menu Items Per Serve Size  Energy (kCal)  \
0  Regular Menu        McVeggie™ Burger          168 g         402.05   
1  Regular Menu    McAloo Tikki Burger®          146 g         339.52   
2  Regular Menu  McSpicy™ Paneer Burger          199 g         652.76   
3  Regular Menu       Spicy Paneer Wrap          250 g         674.68   
4  Regular Menu     American Veg Burger          177 g         512.17   

   Protein (g)  Total fat (g)  Sat Fat (g)  Trans fat (g)  Cholesterols (mg)  \
0        10.24          13.83         5.34           0.16               2.49   
1         8.50          11.31         4.27           0.20               1.47   
2        20.29          39.45        17.12           0.18              21.85   
3        20.96          39.10        19.73           0.26              40.93   
4        15.30          23.45        10.51           0.17              25.24   

   Total carbohydrate (g)  Total Sugars (g)  Added Sugars (g)  Sodium (mg)  
0                   56.54              7.90              4.49       706.13  
1                   50.27              7.05              4.07       545.34  
2                   52.33              8.35              5.27      1074.58  
3                   59.27              3.50              1.08      1087.46  
4                   56.96              7.85              4.76      1051.24

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Menu Category           141 non-null    object 
 1   Menu Items              141 non-null    object 
 2   Per Serve Size          141 non-null    object 
 3   Energy (kCal)           141 non-null    float64
 4   Protein (g)             141 non-null    float64
 5   Total fat (g)           141 non-null    float64
 6   Sat Fat (g)             141 non-null    float64
 7   Trans fat (g)           141 non-null    float64
 8   Cholesterols (mg)       141 non-null    float64
 9   Total carbohydrate (g)  141 non-null    float64
 10  Total Sugars (g)        141 non-null    float64
 11  Added Sugars (g)        141 non-null    float64
 12  Sodium (mg)             140 non-null    float64
dtypes: float64(10), object(3)
memory usage: 14.4+ KB


In [6]:
data.describe()

Energy (kCal)  Protein (g)  Total fat (g)  Sat Fat (g)  Trans fat (g)  \
count     141.000000   141.000000     141.000000   141.000000     141.000000   
mean      244.635461     7.493546       9.991702     4.997589       0.687163   
std       185.554837     8.336863      10.339511     4.900451       6.326136   
min         0.000000     0.000000       0.000000     0.000000       0.000000   
25%       116.360000     0.650000       0.460000     0.280000       0.060000   
50%       219.360000     4.790000       7.770000     4.270000       0.150000   
75%       339.520000    10.880000      14.160000     7.280000       0.220000   
max       834.360000    39.470000      45.180000    20.460000      75.260000   

       Cholesterols (mg)  Total carbohydrate (g)  Total Sugars (g)  \
count         141.000000              141.000000        141.000000   
mean           26.350071               31.190284         15.464894   
std            50.334200               20.602044         15.690202   
min             0.000000                0.000000          0.000000   
25%             1.510000               15.740000          2.330000   
50%             8.390000               30.820000          9.160000   
75%            31.110000               46.000000         26.950000   
max           302.610000               93.840000         64.220000   

       Added Sugars (g)  Sodium (mg)  
count        141.000000   140.000000  
mean          10.336950   362.064143  
std           14.283388   473.160490  
min            0.000000     0.000000  
25%            0.000000    43.895000  
50%            3.640000   152.025000  
75%           19.230000   534.240000  
max           64.220000  2399.490000

In [8]:
data['Energy (kCal)']

0      402.05
1      339.52
2      652.76
3      674.68
4      512.17
        ...  
136     11.23
137     86.40
138     51.03
139     45.08
140     72.25
Name: Energy (kCal), Length: 141, dtype: float64

In [10]:
data.iloc[14]

Menu Category                     Regular Menu
Menu Items                Chicken Kebab Burger
Per Serve Size                           138 g
Energy (kCal)                           357.05
Protein (g)                               8.64
Total fat (g)                            14.02
Sat Fat (g)                               4.84
Trans fat (g)                             0.13
Cholesterols (mg)                         1.51
Total carbohydrate (g)                    47.9
Total Sugars (g)                          5.08
Added Sugars (g)                          3.49
Sodium (mg)                             548.79
Name: 14, dtype: object



---


* Создайте вектор (одномерный массив) размера 10, заполненный нулями

* Создайте вектор размера 10, заполненный числом 5.8

* Создйте массив 3x3x3 со случайными значениями

* Создайте 8x8 матрицу и заполнить её в шахматном порядке

* Cоздайте матрицу 4 на 4 и заполните ее произвольными числами (понадобиться в дальйнешем)


In [13]:
import numpy as np

zeros_10 = np.zeros((1, 10))
zeros_10

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
five_eight = np.array([5.8] * 10)
five_eight

array([5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8])

In [17]:
rand_cube = np.random.sample((3, 3, 3))
rand_cube

array([[[0.16335472, 0.28613374, 0.71122429],
        [0.14430531, 0.97015224, 0.26008682],
        [0.3282585 , 0.77621252, 0.78708285]],

       [[0.0607168 , 0.62155035, 0.34132569],
        [0.89152087, 0.91667156, 0.77810514],
        [0.43178757, 0.78139588, 0.41749701]],

       [[0.40802826, 0.63363603, 0.3868974 ],
        [0.25523774, 0.89208809, 0.97228013],
        [0.67715749, 0.44781414, 0.91679137]]])

In [18]:
chess_fill = np.zeros((8, 8))

val = 1
for i in range(len(chess_fill)):
  for j in range(len(chess_fill[i])):
    if (i + j) % 2 == 0:
      chess_fill[i][j] = val 
      val += 1

chess_fill

array([[ 1.,  0.,  2.,  0.,  3.,  0.,  4.,  0.],
       [ 0.,  5.,  0.,  6.,  0.,  7.,  0.,  8.],
       [ 9.,  0., 10.,  0., 11.,  0., 12.,  0.],
       [ 0., 13.,  0., 14.,  0., 15.,  0., 16.],
       [17.,  0., 18.,  0., 19.,  0., 20.,  0.],
       [ 0., 21.,  0., 22.,  0., 23.,  0., 24.],
       [25.,  0., 26.,  0., 27.,  0., 28.,  0.],
       [ 0., 29.,  0., 30.,  0., 31.,  0., 32.]])

In [19]:
a = np.random.sample((4, 4))
a

array([[0.01759048, 0.94166356, 0.96901029, 0.21284856],
       [0.52432005, 0.92869303, 0.88349076, 0.00412528],
       [0.91499438, 0.55843606, 0.07525388, 0.96337891],
       [0.74831431, 0.64527155, 0.23228629, 0.68230591]])



---



* Возьмите интеграл $\int_{-3}^{10} sin(x)* x^{2} \,dx $
* Найдите определитель, обратную матрицу и собственные значения к матрице из последнего пункта раздела Numpy

In [20]:
from math import sin
from scipy import integrate
from scipy import linalg

f1 = lambda x: sin(x) * x**2
integrate.quad(f1, -3, 10)

(63.57192010714263, 2.177803784883395e-12)

In [22]:
linalg.det(a)

-0.04015846157518563

In [23]:
linalg.inv(a)

array([[ -1.31428523,   2.19281519,   2.99116799,  -3.8266273 ],
       [ -0.10998947,  -3.08353298, -11.1527919 ,  15.80009186],
       [  0.88979626,   3.07431323,   9.93010812, -14.3169374 ],
       [  1.2425278 ,  -0.53541922,   3.88625914,  -4.40594395]])

In [21]:
linalg.eig(a)

(array([ 2.33133811+0.j        , -0.68212665+0.j        ,
         0.02731592+0.15654546j,  0.02731592-0.15654546j]),
 array([[ 0.47310625+0.j        ,  0.78085954+0.j        ,
         -0.10932623+0.14240738j, -0.10932623-0.14240738j],
        [ 0.51004769+0.j        ,  0.02851205+0.j        ,
          0.67422777+0.j        ,  0.67422777-0.j        ],
        [ 0.52670808+0.j        , -0.51374231+0.j        ,
         -0.62177343+0.03606424j, -0.62177343-0.03606424j],
        [ 0.48846742+0.j        , -0.35427995+0.j        ,
         -0.26191081-0.23808556j, -0.26191081+0.23808556j]]))